[tool.poetry]
name = "dump-env"
version = "0.2.2"
description = "A utility tool to create .env files"

license = "MIT"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>"
]

readme = "README.md"  # Markdown files are supported

repository = "https://github.com/sobolevn/dump-env"
homepage = "https://github.com/sobolevn/dump-env"

keywords = [
  "dotenv",
  ".env",
  "tempaltes",
  "secrets",
  "CI/CD"

]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: Implementation :: CPython"
]

[tool.poetry.scripts]
dump-env = "dump_env.cli:main"

[tool.poetry.dependencies]
python = "^3.6"  # taken from setup.py

# all the versions below are defined with poetry add --dev DEPENDENCY_NAME
[tool.poetry.dev-dependencies]
pytest = "^3.8"
pytest-cov = "^2.6"
wemake-python-styleguide = "^0.8.1"
"delegator.py" = "^0.1.1"
safety = "^1.8"
mypy = "^0.711"
