[tool.poetry]
name = "dump-env"
version = "1.4.0"
description = "A utility tool to create .env files"

license = "MIT"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>"
]

readme = "README.md"

repository = "https://github.com/wemake-services/dump-env"
homepage = "https://dump-env.readthedocs.io"

keywords = [
  "dotenv",
  ".env",
  "tempaltes",
  "secrets",
  "CI/CD"
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[tool.poetry.scripts]
dump-env = "dump_env.cli:main"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.test.dependencies]
pytest-cov = "^3.0"
pytest-randomly = "^3.10"
pytest = "^7.0"
"delegator.py" = "^0.1"

wemake-python-styleguide = "^0.16"
flake8-pytest-style = "^1.5"
nitpick = "^0.29"

safety = "^2.1"
mypy = "^0.971"
doc8 = "^0.11"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^5.1"
sphinx-readable-theme = "^1.3"
m2r2 = "^0.3"
tomlkit = "^0.11"


[build-system]
requires = ["poetry>=1.2.0"]
build-backend = "poetry.masonry.api"


[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"
