[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"


[tool.poetry]
name = "dump-env"
version = "1.2.0"
description = "A utility tool to create .env files"

license = "MIT"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>"
]

readme = "README.md"

repository = "https://github.com/sobolevn/dump-env"
homepage = "https://dump-env.readthedocs.io"

keywords = [
  "dotenv",
  ".env",
  "tempaltes",
  "secrets",
  "CI/CD"
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[tool.poetry.scripts]
dump-env = "dump_env.cli:main"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest-cov = "^2.9"
pytest-randomly = "^3.4"
pytest = "^5.4"
"delegator.py" = "^0.1.1"

wemake-python-styleguide = "^0.14"
flake8-pytest-style = "^1.1"
nitpick = "^0.22"

safety = "^1.9"
mypy = "^0.770"

sphinx = "^3.1"
sphinx-readable-theme = "^1.3"
m2r = "^0.2"
doc8 = "^0.8"
tomlkit = "^0.6"


[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
